[versions]
# SLF4J releases: http://www.slf4j.org/news.html
slf4j = "2.0.7"

# H2 releases: https://github.com/h2database/h2database/releases
h2 = "2.2.220"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
